// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/clients": {
            "get": {
                "description": "Requiere headers admin (` + "`" + `user` + "`" + ` y ` + "`" + `token` + "`" + `).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Listar clientes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario admin (MAIN_USER)",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token admin (MAIN_TOKEN)",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Client"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            },
            "post": {
                "description": "Requiere headers admin (` + "`" + `user` + "`" + ` y ` + "`" + `token` + "`" + `). El campo token de la respuesta solo se muestra en este alta.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Registrar cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario admin (MAIN_USER)",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token admin (MAIN_TOKEN)",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Nombre opcional",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/transport.createClientBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.ClientCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/clients/{id}": {
            "put": {
                "description": "Requiere headers admin (` + "`" + `user` + "`" + ` y ` + "`" + `token` + "`" + `). No permite editar el usuario admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Editar cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario admin (MAIN_USER)",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token admin (MAIN_TOKEN)",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "name opcional, rotate_token opcional",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.updateClientBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ClientUpdatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            },
            "delete": {
                "description": "Requiere headers admin (` + "`" + `user` + "`" + ` y ` + "`" + `token` + "`" + `). No permite eliminar el usuario admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Eliminar cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario admin (MAIN_USER)",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token admin (MAIN_TOKEN)",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/clients/{id}/permissions": {
            "get": {
                "description": "Requiere headers admin (` + "`" + `user` + "`" + ` y ` + "`" + `token` + "`" + `).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Obtener permisos de cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario admin (MAIN_USER)",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token admin (MAIN_TOKEN)",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ClientPermissions"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            },
            "put": {
                "description": "Requiere headers admin (` + "`" + `user` + "`" + ` y ` + "`" + `token` + "`" + `). Reemplaza la configuración completa del cliente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Configurar permisos de cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario admin (MAIN_USER)",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token admin (MAIN_TOKEN)",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del cliente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Permisos por categoría",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpsertClientPermissionsBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ClientPermissions"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/main": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Filtros opcionales combinables (query). Requiere header token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maindb"
                ],
                "summary": "Listar maindb",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Desde fecha (YYYY-MM-DD UTC)",
                        "name": "fromdate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Categorías separadas por coma",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por available: true, false, 1 o 0",
                        "name": "avariable",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Máximo de filas (1-1000)",
                        "name": "max",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Orden por created_at",
                        "name": "ord",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "texto plano",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/main/categories": {
            "get": {
                "description": "Endpoint público. Permite filtrar opcionalmente por available con query avariable=true|false|1|0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maindb"
                ],
                "summary": "Contar categorías de maindb",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por available: true, false, 1 o 0",
                        "name": "avariable",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CategoryCountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/main/{id}": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maindb"
                ],
                "summary": "Obtener maindb por id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del registro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Pone available a false. Si ya era false, responde 200 con mensaje informativo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maindb"
                ],
                "summary": "Deshabilitar maindb",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del registro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/newmain": {
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maindb"
                ],
                "summary": "Crear maindb",
                "parameters": [
                    {
                        "description": "category y subtype obligatorios",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.mainCreateBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CategoryCount": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.CategoryCountResponse": {
            "type": "object",
            "properties": {
                "advice": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CategoryCount"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Client": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.ClientCreatedResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.ClientPermissions": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "create_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_create_categories": {
                    "type": "integer"
                },
                "read_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "restricted": {
                    "type": "boolean"
                },
                "write_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ClientUpdatedResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.ErrorJSON": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "model.MaindbWithSync": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subtype": {
                    "type": "string"
                },
                "synced": {
                    "type": "boolean"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "advice": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MaindbWithSync"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.UpsertClientPermissionsBody": {
            "type": "object",
            "properties": {
                "create_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_create_categories": {
                    "type": "integer"
                },
                "read_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "restricted": {
                    "type": "boolean"
                },
                "write_categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "transport.createClientBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "transport.mainCreateBody": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subtype": {
                    "type": "string"
                }
            }
        },
        "transport.updateClientBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "rotate_token": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "TokenAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8005",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Aflujo API",
	Description:      "API REST para maindb: clientes con token (header `token`), alta y listados con estado de sync por cliente.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
